import { GEO_POOLS, type GeneratorConfig } from "./logGenerator";

export interface WorkflowDescriptor {
  title: string;
  description: string;
  isPrivate: boolean;
  trigger: {
    schedule: {
      isActive: boolean;
      isFaulty: boolean;
      trigger: { type: "cron"; cron: string };
      rule: null;
      filterParameters: Record<string, never>;
      timezone: "UTC";
      inputs: Record<string, never>;
    };
  };
  tasks: Record<
    string,
    {
      name: string;
      action: string;
      input: { script: string };
      timeout?: number;
      position?: { x: number; y: number };
      retry?: { count: number; delay: number };
    }
  >;
}

const escapeForTemplateLiteral = (s: string) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

/**
 * Build the embedded JavaScript task code. The code is fully self-contained:
 * all configuration is interpolated as JSON literals so the workflow has no
 * external dependencies.
 */
export const buildJavaScriptTaskCode = (cfg: GeneratorConfig): string => {
  const json = JSON.stringify({
    vertical: cfg.vertical,
    useCase: cfg.useCase,
    scenarioName: cfg.scenarioName,
    customerName: cfg.customerName ?? "",
    logsPerMinute: cfg.logsPerMinute,
    errorRate: cfg.errorRate,
    services: cfg.services,
    hosts: cfg.hosts,
    firstRunAt: new Date().toISOString(),
  });

  return `import { logsClient } from "@dynatrace-sdk/client-classic-environment-v2";

// === Auto-generated by LaunchLog ===
const CFG = ${json};
const BATCH_SECONDS = 120;         // each scheduled run produces 2 minutes of logs

// ---- helpers ----
const r = () => Math.random();
const pick = (a) => a[Math.floor(r() * a.length)];
const intBetween = (a, b) => Math.floor(a + r() * (b - a + 1));
const numBetween = (a, b) => +(a + r() * (b - a)).toFixed(2);
const chance = (p) => r() < p;
const HEX = "0123456789abcdef";
const ALNUM = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const randHex = (n) => Array.from({ length: n }, () => HEX[Math.floor(r() * 16)]).join("");
const randAlnum = (n) => Array.from({ length: n }, () => ALNUM[Math.floor(r() * 36)]).join("");
const randDigits = (n) => Array.from({ length: n }, () => Math.floor(r() * 10)).join("");
const uuidLike = () => randHex(8) + "-" + randHex(4) + "-" + randHex(4) + "-" + randHex(4) + "-" + randHex(12);

const pickLevel = (errorRate) => {
  const errP = errorRate;
  const warnP = errorRate * 1.5;
  const debugP = 0.07;
  const roll = r();
  if (roll < errP) return "ERROR";
  if (roll < errP + warnP) return "WARN";
  if (roll < errP + warnP + debugP) return "DEBUG";
  return "INFO";
};

// ---- per-vertical payload generators (mirrors logGenerator.ts) ----
const PACKS = ${buildPackBundle()};

// ---- INFO-level event.type variants per use case ----
// Each pack's ok() emits a single event.type, which would make the
// "Event Mix Over Time" stacked-bar chart show one series. These variants
// override event.type on INFO logs so the mix is colorful and meaningful.
const INFO_TYPE_VARIANTS = {
  "financial/payments":         ["TRANSACTION_COMPLETED","CARD_AUTHORIZED","SETTLEMENT","REFUND_ISSUED","WALLET_TOPUP"],
  "financial/fraud":            ["FRAUD_SCORED","TRANSACTION_REVIEWED","RULE_EVALUATED","DEVICE_FINGERPRINT","WHITELIST_HIT"],
  "financial/trading":          ["ORDER_EXECUTED","ORDER_PLACED","ORDER_AMENDED","QUOTE_REQUEST","TRADE_CONFIRMED"],
  "healthcare/patient_portal":  ["PATIENT_ACTION","RECORD_VIEW","APPOINTMENT_BOOKED","MESSAGE_SENT","PRESCRIPTION_REFILL"],
  "healthcare/claims":          ["CLAIM_SUBMITTED","CLAIM_APPROVED","CLAIM_PAID","CLAIM_PENDED","ELIGIBILITY_CHECK"],
  "healthcare/ehr":             ["HL7_MESSAGE","HL7_ADT","HL7_ORM","HL7_ORU","HL7_ACK"],
  "retail/orders":              ["ORDER_CREATED","ORDER_PICKED","ORDER_SHIPPED","ORDER_DELIVERED","ORDER_CONFIRMED"],
  "retail/inventory":           ["STOCK_CHECK","REORDER_TRIGGERED","RECEIVING","CYCLE_COUNT","TRANSFER"],
  "retail/cx":                  ["BROWSE","SEARCH","ADD_TO_CART","WISHLIST_ADD","PRODUCT_VIEW"],
  "telco/network":              ["KPI_OK","HEALTH_CHECK","UTILIZATION_SAMPLE","HANDOFF","SIGNAL_REPORT"],
  "telco/billing":              ["USAGE_EVENT","CDR_RATED","INVOICE_GENERATED","PAYMENT_POSTED","ACCOUNT_ADJUSTED"],
  "telco/care":                 ["TICKET_UPDATE","CALL_LOGGED","CHAT_LOGGED","KNOWLEDGE_LOOKUP","SURVEY_RESPONSE"],
  "manufacturing/production":   ["UNIT_PRODUCED","SHIFT_START","OEE_SAMPLE","CHANGEOVER","INSPECTION_PASS"],
  "manufacturing/quality":      ["INSPECTION_PASS","SAMPLE_TAKEN","CALIBRATION_OK","AUDIT_LOGGED","SPEC_VERIFIED"],
  "manufacturing/supply_chain": ["PO_EVENT","ASN_RECEIVED","GOODS_RECEIPT","SUPPLIER_CONFIRMED","SHIPMENT_DISPATCHED"],
  "insurance/claims":           ["CLAIM_OPENED","ADJUSTER_ASSIGNED","INSPECTION_BOOKED","PAYMENT_RELEASED","CLAIM_CLOSED"],
  "insurance/underwriting":     ["QUOTE_REQUESTED","RISK_SCORED","POLICY_ISSUED","DOCUMENT_UPLOADED","BIND_CONFIRMED"],
  "insurance/policy":           ["POLICY_RENEWED","ENDORSEMENT","BENEFICIARY_UPDATED","ADDRESS_CHANGE","DOCUMENT_GENERATED"],
  "gaming/sessions":            ["MATCH_START","MATCH_END","LOGIN","LEVEL_UP","ACHIEVEMENT"],
  "gaming/monetization":        ["IAP","STORE_VIEW","OFFER_SHOWN","BUNDLE_PURCHASED","CURRENCY_EARNED"],
  "gaming/live_ops":            ["LIVEOPS","HEALTH_CHECK","DEPLOY_OK","SCALE_OUT","CONFIG_PUSH"],
  "logistics/last_mile":        ["DELIVERY_EVENT","SCAN_PICKED","SCAN_OUT_FOR_DELIVERY","SCAN_DELIVERED","ROUTE_OPTIMIZED"],
  "logistics/warehouse":        ["WAREHOUSE_EVENT","INBOUND_RECEIVED","PUTAWAY","PICK","SHIP_CONFIRM"],
  "logistics/fleet":            ["LOCATION_UPDATE","ROUTE_STARTED","ROUTE_COMPLETED","FUEL_LEVEL","DRIVER_LOGIN"],
  "energy/smart_grid":          ["GRID_EVENT","SUBSTATION_OK","LOAD_BALANCED","SWITCH_OPERATED","TELEMETRY_SAMPLE"],
  "energy/outage":              ["RESTORED","CREW_DISPATCHED","ETA_UPDATED","CUSTOMER_NOTIFIED","STATUS_UPDATE"],
  "energy/metering":            ["METER_READ","INTERVAL_READ","CONNECT","DISCONNECT","COMMAND_ACK"],
  "automotive/telematics":      ["TRIP_START","TRIP_END","HEARTBEAT","DTC_CLEARED","GEOFENCE_ENTRY"],
  "automotive/ota_updates":     ["INSTALL_SUCCESS","DOWNLOAD_STARTED","DOWNLOAD_COMPLETED","VERIFY_OK","CAMPAIGN_TARGETED"],
  "automotive/ev_charging":     ["EV_SESSION","SESSION_STARTED","SESSION_ENDED","RFID_AUTH","RATE_APPLIED"],
  "pos/transactions":           ["SALE","ITEM_SCANNED","TENDER_APPLIED","DISCOUNT_APPLIED","RECEIPT_PRINTED"],
  "pos/terminal_health":        ["HEARTBEAT","PERIPHERAL_OK","FIRMWARE_OK","CONFIG_SYNC","NETWORK_OK"],
  "pos/kitchen":                ["KDS_EVENT","ORDER_RECEIVED","ORDER_FIRED","ORDER_BUMPED","STATION_READY"],
  "airlines/flight_ops":        ["FLIGHT_EVENT","DEPARTED","ARRIVED","TAXIING","GATE_ASSIGNED"],
  "airlines/passenger":         ["CHECK_IN","BOARDING","BAG_TAGGED","SEAT_ASSIGNED","UPGRADE"],
  "airlines/ground_ops":        ["GROUND_OPS","TURNAROUND_OK","FUEL_LOADED","CARGO_LOADED","PUSHBACK"],
  "iot/device_fleet":           ["HEARTBEAT","TELEMETRY","CONFIG_SYNC","UPDATE_CHECK","REGISTRATION"],
  "iot/sensor_telemetry":       ["SENSOR_READING","SAMPLE","CALIBRATION","BASELINE","HEARTBEAT"],
  "iot/firmware":               ["INSTALL_SUCCESS","DOWNLOAD_STARTED","VERIFY_OK","REBOOT","CAMPAIGN_TARGETED"],
  "media/video_delivery":                  ["PLAYBACK_START","PLAYBACK_END","QUALITY_SWITCH","SEEK","HEARTBEAT"],
  "media/live_streaming":                  ["LIVE_STREAM","SEGMENT_DELIVERED","ENCODER_OK","CDN_HIT","HEALTH_CHECK"],
  "media/ad_insertion":                    ["AD_REQUEST","AD_IMPRESSION","AD_COMPLETE","AD_CLICK","BEACON"],
  "cash_valuables/cash_in_transit":        ["SHIPMENT_DISPATCHED","VEHICLE_DEPARTED","CHECKPOINT_CLEARED","DELIVERY_CONFIRMED","MANIFEST_SIGNED"],
  "cash_valuables/vault_operations":       ["VAULT_DEPOSIT","VAULT_WITHDRAWAL","VAULT_AUDIT","RECONCILIATION_OK","ACCESS_GRANTED"],
  "cash_valuables/counterfeit_detection":  ["NOTE_VALIDATED","BATCH_ACCEPTED","SENSOR_CALIBRATED","OPERATOR_VERIFIED","SHIFT_STARTED"],
  "digital_retail/terminal_management":    ["TERMINAL_HEARTBEAT","TERMINAL_ONLINE","CONFIG_PUSHED","SOFTWARE_UPDATED","SELF_TEST_PASSED"],
  "digital_retail/self_checkout":          ["SCO_TRANSACTION","ITEM_SCANNED","PAYMENT_PROCESSED","RECEIPT_PRINTED","SESSION_STARTED"],
  "digital_retail/loyalty_receipts":       ["LOYALTY_TRANSACTION","POINTS_ACCRUED","RECEIPT_SENT","OFFER_REDEEMED","MEMBER_VERIFIED"],
  "atm_services/atm_fleet_health":         ["ATM_HEARTBEAT","ATM_ONLINE","SELF_TEST_PASSED","CONFIG_SYNC","PERIODIC_CHECK"],
  "atm_services/cash_replenishment":       ["REPLENISHMENT_COMPLETED","CASSETTE_LOADED","CREW_ARRIVED","AUDIT_COMPLETED","CASH_COUNTED"],
  "atm_services/atm_transactions":         ["ATM_TRANSACTION_COMPLETED","CARD_READ","PIN_VALIDATED","DISPENSER_OK","RECEIPT_ISSUED"],
  "__default__":                           ["EVENT","HEARTBEAT","SAMPLE","ACTION","CHECK"],
};

// ---- geo / IP enrichment ----
const GEO_POOLS = ${buildGeoPoolsBundle()};
const PUBLIC_IP_PREFIXES = ["203.0","185.220","52.84","34.102","104.16","172.217","151.101","18.232","13.107","199.232","208.67","8.8","1.1","23.45","67.220","76.76","162.158","192.0","200.144"];
const randPublicIp = () => pick(PUBLIC_IP_PREFIXES) + "." + intBetween(1, 254) + "." + intBetween(1, 254);
const pickGeo = () => {
  const pool = GEO_POOLS[CFG.vertical] || GEO_POOLS.financial;
  return pool[Math.floor(r() * pool.length)];
};
const geoFields = () => {
  const g = pickGeo();
  return {
    "source.ip": randPublicIp(),
    "geo.country": g.country,
    "geo.city": g.city,
    "geo.lat": g.lat,
    "geo.lon": g.lon,
    "geo.region": g.region,
  };
};

const baseFields = (ts) => {
  const host = pick(CFG.hosts);
  return {
    timestamp: ts.toISOString(),
    "service.name": pick(CFG.services),
    "service.version": "v" + intBetween(1, 5) + "." + intBetween(0, 20) + "." + intBetween(0, 30),
    "trace.id": uuidLike(),
    "span.id": randHex(16),
    "dt.entity.host": host,
    "host.name": host,
    "host.ip": randPublicIp(),
    environment: chance(0.9) ? "production" : "staging",
    "log.generator": "dt-biz-log-gen",
    "scenario.vertical": CFG.vertical,
    "scenario.usecase": CFG.useCase,
    "scenario.name": CFG.scenarioName,
    "scenario.customer": CFG.customerName,
    ...geoFields(),
  };
};

const buildLine = (ts, forcedLevel) => {
  const level = forcedLevel || pickLevel(CFG.errorRate);
  const base = baseFields(ts);
  const pack = PACKS[CFG.vertical + "/" + CFG.useCase] || PACKS["__default__"];
  let payload;
  if (level === "ERROR") payload = pack.err();
  else if (level === "WARN") payload = pack.warn();
  else payload = pack.ok();
  // Diversify info-level event.type so "Event Mix Over Time" shows multiple
  // stacked categories. Each pack defaults to one OK event.type which would
  // otherwise dominate the chart with a single series.
  if (level === "INFO") {
    const variants = INFO_TYPE_VARIANTS[CFG.vertical + "/" + CFG.useCase];
    if (variants && variants.length > 0) {
      payload = { ...payload, "event.type": pick(variants) };
    }
  }
  // business.category mirrors event.type so dashboards can filter / group by
  // a single, always-present field regardless of pack branch.
  return {
    ...base,
    "log.level": level,
    ...payload,
    "business.category": payload["event.type"],
    content: payload.message || "",
  };
};

// Guarantee a minimum number of ERROR + WARN events per time window so every
// "error rate", "fraud alert", "stockout" etc. dashboard tile has data. Floor
// is roughly 5% errors + 10% warns of the window's record count, with sensible
// minimums. Pushes directly into the shared lines array.
const ensureMinSeverity = (lines, sliceStartIdx, windowStart, windowEnd, target) => {
  const minErr = Math.max(3, Math.ceil(target * 0.05));
  const minWarn = Math.max(5, Math.ceil(target * 0.10));
  let errs = 0, warns = 0;
  for (let i = sliceStartIdx; i < lines.length; i++) {
    if (lines[i]["log.level"] === "ERROR") errs++;
    else if (lines[i]["log.level"] === "WARN") warns++;
  }
  while (errs < minErr) {
    lines.push(buildLine(new Date(windowStart + Math.floor(r() * (windowEnd - windowStart))), "ERROR"));
    errs++;
  }
  while (warns < minWarn) {
    lines.push(buildLine(new Date(windowStart + Math.floor(r() * (windowEnd - windowStart))), "WARN"));
    warns++;
  }
};

export default async function ({ execution_id }) {
  const target = Math.max(1, Math.round((CFG.logsPerMinute / 60) * BATCH_SECONDS));
  const now = Date.now();
  const lines = [];

  // 3-hour historical backfill on first run, at ~1× live rate (≈ lpm per bin)
  // so dashboards look populated immediately. Capped for safety.
  const isFirstRun = now - new Date(CFG.firstRunAt).getTime() < 180_000;
  if (isFirstRun) {
    const BACKFILL_INTERVALS = 36;           // 36 × 5-min intervals = 3 h
    const INTERVAL_MS = 5 * 60 * 1000;
    const perBin = Math.max(1, Math.round((CFG.logsPerMinute / 60) * 60)); // 1 minute of logs per 5-min bin
    const backfillStart = now - BACKFILL_INTERVALS * INTERVAL_MS;
    for (let iv = 0; iv < BACKFILL_INTERVALS; iv++) {
      const start = backfillStart + iv * INTERVAL_MS;
      const before = lines.length;
      for (let i = 0; i < perBin; i++) {
        lines.push(buildLine(new Date(start + Math.floor(r() * INTERVAL_MS))));
      }
      // Per-bin severity floor so trend tiles always show error/warn series.
      ensureMinSeverity(lines, before, start, start + INTERVAL_MS, perBin);
    }
    console.log("[" + execution_id + "] backfill: " + lines.length + " logs across 3 h for scenario=" + CFG.scenarioName);
  }

  // Regular live batch
  const liveStart = now - BATCH_SECONDS * 1000;
  const liveStartIdx = lines.length;
  let t = liveStart;
  for (let i = 0; i < target; i++) {
    t += intBetween(50, 500);
    if (t > now) t = now;
    lines.push(buildLine(new Date(t)));
  }
  // Guarantee severity floor in the live window too — keeps "errors in last
  // minute" tiles populated on every refresh.
  ensureMinSeverity(lines, liveStartIdx, liveStart, now, target);

  console.log("[" + execution_id + "] ingesting " + lines.length + " logs for scenario=" + CFG.scenarioName);

  // Logs Ingest API accepts an array of log records; chunk to keep payload safe.
  const CHUNK = 500;
  for (let i = 0; i < lines.length; i += CHUNK) {
    const slice = lines.slice(i, i + CHUNK);
    await logsClient.storeLog({ type: "application/json", body: slice });
  }
  return { ingested: lines.length, scenario: CFG.scenarioName };
}
`;
};

/** Inline GEO_POOLS as JSON literal for the workflow script. */
const buildGeoPoolsBundle = (): string => JSON.stringify(GEO_POOLS);

/**
 * Pack bundle is the same per-vertical payload generator dictionary, inlined
 * into the workflow's JS task. Keep this synchronized with logGenerator.ts.
 */
const buildPackBundle = (): string => `(() => {
  const FIN_PAYMENTS = {
    ok() {
      const id = "TXN-" + randAlnum(12);
      const amount = numBetween(5, 5000);
      const cur = pick(["USD","EUR","GBP"]);
      return { "event.type":"TRANSACTION_COMPLETED","transaction.id":id,"transaction.amount":amount,"transaction.currency":cur,
        "transaction.type":pick(["PURCHASE","REFUND","TRANSFER"]),"payment.method":pick(["CARD","ACH","WIRE","DIGITAL_WALLET"]),
        "card.network":pick(["VISA","MASTERCARD","AMEX","DISCOVER"]),"merchant.category":pick(["RETAIL","TRAVEL","FOOD","UTILITIES","HEALTHCARE"]),
        "customer.tier":pick(["PLATINUM","GOLD","SILVER","STANDARD"]),latency_ms:intBetween(20,450),
        "fraud.score":+numBetween(0.01,0.15),message:"Transaction "+id+" authorized for "+amount+" "+cur };
    },
    err() {
      const reason = pick(["INSUFFICIENT_FUNDS","CARD_EXPIRED","FRAUD_BLOCK","VELOCITY_LIMIT","INVALID_CVV"]);
      return { "event.type":"TRANSACTION_DECLINED","decline.reason":reason,"transaction.amount":numBetween(5,5000),
        "customer.tier":pick(["PLATINUM","GOLD","SILVER","STANDARD"]),latency_ms:intBetween(5,50),
        message:"Transaction declined: "+reason };
    },
    warn() {
      const score=+numBetween(0.75,0.99); const action=pick(["STEP_UP_AUTH","BLOCK","FLAG"]);
      return { "event.type":"FRAUD_ALERT","fraud.score":score,
        "fraud.reason":pick(["UNUSUAL_LOCATION","VELOCITY_SPIKE","DEVICE_MISMATCH","AMOUNT_ANOMALY"]),
        "action.taken":action,message:"High fraud score "+score+" — action: "+action };
    },
  };
  const FIN_FRAUD_BASE = () => ({ "model.version":pick(["v3.2.1","v3.1.8","v2.9.4"]),"features.evaluated":intBetween(15,120),
    "inference.latency_ms":intBetween(5,80),"rule.triggered":pick(["VELOCITY_24H","GEO_ANOMALY","DEVICE_FINGERPRINT","BEHAVIOR_MODEL","NETWORK_GRAPH"]) });
  const FIN_FRAUD = {
    ok() { return { ...FIN_FRAUD_BASE(),"event.type":"FRAUD_SCORED","fraud.score":+numBetween(0.0,0.4),message:"Transaction scored low risk" }; },
    warn() { return { ...FIN_FRAUD_BASE(),"event.type":"FRAUD_ELEVATED","fraud.score":+numBetween(0.6,0.85),"case.id":"CASE-"+randDigits(7),message:"Elevated risk — case opened" }; },
    err() { return { ...FIN_FRAUD_BASE(),"event.type":"FRAUD_BLOCKED","fraud.score":+numBetween(0.85,0.99),"case.id":"CASE-"+randDigits(7),message:"Transaction blocked by fraud engine" }; },
  };
  const FIN_TRADING = {
    ok() { return { "event.type":"ORDER_EXECUTED","order.id":"ORD-"+randAlnum(10),"instrument.symbol":pick(["AAPL","MSFT","NVDA","TSLA","JPM","GOOGL","AMZN"]),
      side:pick(["BUY","SELL"]),quantity:intBetween(10,5000),price:+numBetween(20,950),latency_ms:intBetween(1,80),
      venue:pick(["NYSE","NASDAQ","ARCA","BATS"]),message:"Order executed" }; },
    err() { return { "event.type":"ORDER_REJECTED","reject.reason":pick(["RISK_LIMIT","INSUFFICIENT_MARGIN","STALE_QUOTE","MARKET_CLOSED"]),latency_ms:intBetween(1,25),message:"Order rejected by risk engine" }; },
    warn() { return { "event.type":"MARKET_DATA_LAG","lag_ms":intBetween(150,2000),"feed.id":pick(["FEED-A","FEED-B","FEED-C"]),message:"Market data feed lagging beyond threshold" }; },
  };
  const HC_PORTAL = {
    ok() { const action=pick(["LOGIN","VIEW_RECORDS","BOOK_APPOINTMENT","DOWNLOAD_REPORT","MESSAGE_PROVIDER"]); const id="PT-"+randDigits(8);
      return { "event.type":"PATIENT_ACTION",action,"patient.id":id,department:pick(["CARDIOLOGY","ONCOLOGY","PEDIATRICS","ORTHOPEDICS","GENERAL"]),
        "session.duration_ms":intBetween(500,120000),"mfa.method":pick(["SMS","TOTP","BIOMETRIC"]),
        "record.type":pick(["LAB_RESULT","IMAGING","PRESCRIPTION","VISIT_SUMMARY"]),latency_ms:intBetween(80,2000),
        "hipaa.compliant":true,message:"Patient "+id+" — "+action+" completed" }; },
    err() { const c=pick(["HL7_PARSE_ERROR","TIMEOUT","AUTH_FAILURE","RECORD_LOCKED"]); const t=pick(["ADT_A01","ORU_R01","ORM_O01","RDS_O13"]);
      return { "event.type":"EHR_INTEGRATION_FAILURE","error.code":c,"hl7.message_type":t,"retry.count":intBetween(0,3),
        message:"EHR integration error: "+c+" for message type "+t }; },
    warn() { return { "event.type":"SLOW_RESPONSE",endpoint:pick(["/records","/appointments","/labs","/messages"]),latency_ms:intBetween(2500,6000),message:"Patient portal endpoint exceeding SLO" }; },
  };
  const HC_CLAIMS_BASE = () => {
    const status = pick(["SUBMITTED","IN_REVIEW","APPROVED","DENIED","PENDING_INFO"]);
    const id = "CLM-"+randDigits(10);
    const f = { "event.type":"CLAIM_EVENT","claim.id":id,"claim.status":status,
      "claim.type":pick(["MEDICAL","DENTAL","VISION","PHARMACY","BEHAVIORAL"]),
      "claim.amount":+numBetween(50,85000),"diagnosis.code":pick(["J20.9","M54.5","K21.0","I10","E11.9"]),
      "processing.time_ms":intBetween(200,15000),"auto.adjudicated":chance(0.7),"sla.met":chance(0.85),
      message:"Claim "+id+" — "+status };
    if (status==="DENIED") f["denial.reason"] = pick(["NOT_COVERED","AUTH_REQUIRED","DUPLICATE","MISSING_INFO"]);
    return f;
  };
  const HC_CLAIMS = { ok:HC_CLAIMS_BASE, err(){ return {...HC_CLAIMS_BASE(),"claim.status":"DENIED","denial.reason":pick(["NOT_COVERED","AUTH_REQUIRED","DUPLICATE","MISSING_INFO"]),message:"Claim denied"}; },
    warn(){ return {...HC_CLAIMS_BASE(),"claim.status":"PENDING_INFO",message:"Claim pending additional information"}; } };
  const HC_EHR = {
    ok(){ return { "event.type":"HL7_MESSAGE","hl7.message_type":pick(["ADT_A01","ORU_R01","ORM_O01","RDS_O13","MDM_T02"]),
      facility:pick(["MAIN_HOSPITAL","WEST_CLINIC","EAST_CLINIC","PEDS_CENTER"]),latency_ms:intBetween(20,600),message:"HL7 message processed" }; },
    err(){ return { "event.type":"HL7_FAILURE","error.code":pick(["PARSE_ERROR","ACK_TIMEOUT","VALIDATION_FAILED"]),"retry.count":intBetween(0,3),message:"HL7 message failed processing" }; },
    warn(){ return { "event.type":"HL7_DELAY",latency_ms:intBetween(2500,8000),message:"HL7 message processing exceeded SLO" }; },
  };
  const RETAIL_ORDERS = {
    ok(){ const status=pick(["PLACED","CONFIRMED","PICKING","PACKED","SHIPPED","DELIVERED"]); const id="ORD-"+randDigits(10);
      return { "event.type":"ORDER_EVENT","order.id":id,"order.status":status,"order.value":+numBetween(9.99,2500),"order.items":intBetween(1,12),
        "customer.segment":pick(["NEW","RETURNING","LOYALTY","VIP"]),"product.category":pick(["ELECTRONICS","APPAREL","HOME","BEAUTY","SPORTS","FOOD"]),
        "warehouse.id":pick(["WH-EAST","WH-WEST","WH-CENTRAL","WH-NORTH"]),carrier:pick(["FEDEX","UPS","USPS","DHL","AMAZON_LOGISTICS"]),
        "delivery.sla":pick(["SAME_DAY","NEXT_DAY","2_DAY","STANDARD"]),latency_ms:intBetween(50,3000),message:"Order "+id+" — "+status }; },
    err(){ const id="ORD-"+randDigits(10); return { "event.type":"ORDER_EVENT","order.id":id,"order.status":"CANCELLED","cancel.reason":pick(["INVENTORY","PAYMENT_FAILED","FRAUD","CUSTOMER"]),latency_ms:intBetween(30,800),message:"Order "+id+" — CANCELLED" }; },
    warn(){ const id="ORD-"+randDigits(10); return { "event.type":"ORDER_EVENT","order.id":id,"order.status":"RETURNED","return.reason":pick(["DEFECTIVE","WRONG_ITEM","NO_LONGER_NEEDED"]),message:"Order "+id+" — RETURNED" }; },
  };
  const RETAIL_INVENTORY = {
    ok(){ return { "event.type":"STOCK_CHECK",sku:"SKU-"+randAlnum(8),"warehouse.id":pick(["WH-EAST","WH-WEST","WH-CENTRAL","WH-NORTH"]),qty:intBetween(0,5000),latency_ms:intBetween(5,100),message:"Stock level read" }; },
    err(){ return { "event.type":"STOCKOUT",sku:"SKU-"+randAlnum(8),"warehouse.id":pick(["WH-EAST","WH-WEST","WH-CENTRAL","WH-NORTH"]),message:"Stock-out detected" }; },
    warn(){ return { "event.type":"REORDER_TRIGGERED",sku:"SKU-"+randAlnum(8),threshold:intBetween(5,50),message:"Replenishment threshold reached" }; },
  };
  const RETAIL_CX = {
    ok(){ return { "event.type":"BROWSE","page.type":pick(["CATEGORY","PRODUCT","SEARCH","HOME"]),"session.id":uuidLike(),latency_ms:intBetween(40,600),message:"Page rendered" }; },
    err(){ return { "event.type":"CHECKOUT_FAILURE","error.code":pick(["PAYMENT_DECLINED","INVENTORY_GONE","ADDRESS_INVALID"]),message:"Checkout failed" }; },
    warn(){ return { "event.type":"CART_ABANDONED","cart.value":+numBetween(15,600),items:intBetween(1,7),message:"Cart abandoned after 30m" }; },
  };
  const TELCO_NETWORK_BASE = () => {
    const node = "NODE-"+randHex(6).toUpperCase();
    const t = pick(["PACKET_LOSS","LATENCY","THROUGHPUT","AVAILABILITY","HANDOFF"]);
    const unit = (t==="PACKET_LOSS"||t==="AVAILABILITY")?"PERCENT":(t==="LATENCY"?"MS":"MBPS");
    let v; switch(t){case "PACKET_LOSS":v=+numBetween(0,4);break;case "AVAILABILITY":v=+numBetween(98,100);break;case "LATENCY":v=intBetween(8,120);break;case "THROUGHPUT":v=+numBetween(50,950);break;default:v=intBetween(0,50);}
    return { "event.type":"NETWORK_EVENT","node.id":node,"node.type":pick(["ENB","GNB","CORE","EDGE","BSC"]),
      region:pick(["NORTHEAST","SOUTHEAST","MIDWEST","WEST","SOUTHWEST"]),"metric.type":t,"metric.value":v,"metric.unit":unit,
      "threshold.breach":chance(0.15),technology:pick(["4G","5G","WIFI6","FIBER"]),"subscriber.impact":intBetween(0,50000),
      "ticket.priority":pick(["P1","P2","P3","P4"]),message:"Network event on "+node+": "+t+" = "+v+unit };
  };
  const TELCO_NETWORK = { ok:TELCO_NETWORK_BASE,
    err(){ return { ...TELCO_NETWORK_BASE(),"event.type":"NETWORK_OUTAGE","threshold.breach":true,"ticket.priority":pick(["P1","P2"]),message:"Outage detected — ticket auto-opened" }; },
    warn(){ return { ...TELCO_NETWORK_BASE(),"event.type":"DEGRADATION","threshold.breach":true,message:"Network performance degrading" }; } };
  const TELCO_BILLING = {
    ok(){ return { "event.type":"USAGE_EVENT","subscriber.id":"SUB-"+randDigits(9),"usage.type":pick(["VOICE","DATA","SMS","ROAMING"]),"usage.amount":+numBetween(0.1,250),latency_ms:intBetween(10,200),message:"Usage rated" }; },
    err(){ return { "event.type":"RATING_FAILURE","error.code":pick(["UNKNOWN_PLAN","TARIFF_MISSING","OVERFLOW"]),message:"Failed to rate usage event" }; },
    warn(){ return { "event.type":"PROVISIONING_DELAY","subscriber.id":"SUB-"+randDigits(9),delay_ms:intBetween(5000,30000),message:"Activation delayed beyond SLA" }; },
  };
  const TELCO_CARE = {
    ok(){ return { "event.type":"TICKET_EVENT","ticket.id":"TKT-"+randDigits(8),action:pick(["CREATED","UPDATED","RESOLVED","ESCALATED"]),priority:pick(["P1","P2","P3","P4"]),latency_ms:intBetween(50,1500),message:"Care ticket processed" }; },
    err(){ return { "event.type":"ROUTING_FAILURE","ticket.id":"TKT-"+randDigits(8),message:"Ticket routing failed" }; },
    warn(){ return { "event.type":"SLA_RISK","ticket.id":"TKT-"+randDigits(8),"minutes.until.breach":intBetween(2,30),message:"Ticket approaching SLA breach" }; },
  };
  const MFG_BASE = () => ({ "event.type":"PRODUCTION_EVENT","line.id":"LINE-"+randDigits(2),"machine.id":"MCH-"+randAlnum(6),
    "machine.type":pick(["CNC","ROBOT","CONVEYOR","PRESS","INSPECTION"]),shift:pick(["MORNING","AFTERNOON","NIGHT"]),latency_ms:intBetween(2,100) });
  const MFG_PRODUCTION = {
    ok(){ const b=MFG_BASE(); return { ...b,"event.subtype":"CYCLE_COMPLETE","units.produced":intBetween(1,500),"defect.rate":+numBetween(0,2),"oee.score":+numBetween(80,98),message:b["machine.id"]+" — CYCLE_COMPLETE on "+b["line.id"] }; },
    err(){ const b=MFG_BASE(); return { ...b,"event.subtype":"DOWNTIME_START","downtime.reason":pick(["BREAKDOWN","QUALITY_HOLD","MATERIAL_SHORTAGE"]),"oee.score":+numBetween(65,80),message:b["machine.id"]+" — DOWNTIME_START on "+b["line.id"] }; },
    warn(){ const b=MFG_BASE(); return { ...b,"event.subtype":"DEFECT_DETECTED","defect.rate":+numBetween(2,8),"oee.score":+numBetween(70,88),message:b["machine.id"]+" — DEFECT_DETECTED on "+b["line.id"] }; },
  };
  const MFG_QUALITY = {
    ok(){ return { "event.type":"INSPECTION",result:"PASS","lot.id":"LOT-"+randAlnum(8),"defect.rate":+numBetween(0,1.5),message:"Inspection passed" }; },
    err(){ return { "event.type":"INSPECTION",result:"FAIL","defect.code":pick(["DIM_OUT_OF_SPEC","SURFACE_DEFECT","WELD_FAULT","TORQUE_FAIL"]),"lot.id":"LOT-"+randAlnum(8),message:"Inspection failed — lot held" }; },
    warn(){ return { "event.type":"INSPECTION",result:"MARGINAL","lot.id":"LOT-"+randAlnum(8),message:"Inspection marginal" }; },
  };
  const MFG_SUPPLY = {
    ok(){ return { "event.type":"PO_EVENT","po.id":"PO-"+randDigits(8),action:pick(["CREATED","ACK","SHIPPED","RECEIVED"]),"supplier.id":"SUP-"+randDigits(4),message:"Purchase order processed" }; },
    err(){ return { "event.type":"SUPPLIER_SLA_BREACH","supplier.id":"SUP-"+randDigits(4),"delay.days":intBetween(1,14),message:"Supplier missed delivery SLA" }; },
    warn(){ return { "event.type":"SUPPLIER_SLA_RISK","supplier.id":"SUP-"+randDigits(4),"minutes.until.breach":intBetween(60,600),message:"Supplier nearing SLA threshold" }; },
  };
  const INS_CLAIMS_BASE = () => {
    const id="IC-"+randDigits(10); const status=pick(["FNOL_RECEIVED","ASSIGNED","INSPECTION","ESTIMATE","APPROVED","DENIED","CLOSED"]);
    return { "event.type":"CLAIM_LIFECYCLE","claim.id":id,"policy.type":pick(["AUTO","HOME","LIFE","COMMERCIAL","HEALTH"]),
      "claim.status":status,"claim.severity":pick(["MINOR","MODERATE","MAJOR","CATASTROPHIC"]),"claim.amount":+numBetween(500,2500000),
      "days.open":intBetween(0,120),"adjuster.id":"ADJ-"+randDigits(4),"fraud.indicator":chance(0.08),
      "sla.status":pick(["ON_TRACK","AT_RISK","BREACHED"]),message:"Claim "+id+" — "+status };
  };
  const INS_CLAIMS = { ok:INS_CLAIMS_BASE, err(){ return { ...INS_CLAIMS_BASE(),"claim.status":"DENIED","sla.status":"BREACHED" }; },
    warn(){ return { ...INS_CLAIMS_BASE(),"sla.status":"AT_RISK" }; } };
  const INS_UW = {
    ok(){ return { "event.type":"UNDERWRITING","quote.id":"QT-"+randDigits(8),"policy.type":pick(["AUTO","HOME","LIFE","COMMERCIAL"]),"risk.score":+numBetween(0,1),decision:pick(["APPROVED","REFER","DECLINED"]),premium:+numBetween(120,8000),latency_ms:intBetween(80,2200),message:"Underwriting decision recorded" }; },
    err(){ return { "event.type":"UNDERWRITING_ERROR","error.code":pick(["MODEL_TIMEOUT","DATA_MISSING","RULES_FAILURE"]),message:"Underwriting flow errored" }; },
    warn(){ return { "event.type":"MANUAL_REFERRAL","quote.id":"QT-"+randDigits(8),message:"Quote referred to senior underwriter" }; },
  };
  const INS_POLICY = {
    ok(){ return { "event.type":"POLICY_EVENT","policy.id":"POL-"+randDigits(9),action:pick(["RENEWAL","ENDORSEMENT","CANCELLATION","ISSUE"]),latency_ms:intBetween(50,1200),message:"Policy event processed" }; },
    err(){ return { "event.type":"POLICY_FAILURE","error.code":pick(["BILLING_REJECT","DOC_GEN_FAIL","STATE_FILING_FAIL"]),message:"Policy operation failed" }; },
    warn(){ return { "event.type":"POLICY_LAPSE_RISK","policy.id":"POL-"+randDigits(9),"days.to.lapse":intBetween(1,14),message:"Policy approaching lapse" }; },
  };
  const GAME_BASE = () => {
    const id="PLR-"+randDigits(8); const region=pick(["NA","EU","APAC","LATAM","MEA"]);
    return { "event.type":"PLAYER_EVENT","player.id":id,"player.level":intBetween(1,100),"player.region":region,
      "game.mode":pick(["RANKED","CASUAL","TOURNAMENT","PRACTICE"]),latency_ms:intBetween(15,250),
      "server.id":"SRV-"+region+"-"+randDigits(3),"anti_cheat.flag":chance(0.01) };
  };
  const GAME_SESSIONS = {
    ok(){ const b=GAME_BASE(); const sub=pick(["LOGIN","MATCH_START","MATCH_END","PURCHASE","ACHIEVEMENT"]); const ex={};
      if(sub==="MATCH_END"){ ex["match.duration_ms"]=intBetween(120000,3600000); ex["match.result"]=pick(["WIN","LOSS","DRAW"]); }
      return { ...b,"event.subtype":sub,...ex,message:"Player "+b["player.id"]+" — "+sub }; },
    err(){ const b=GAME_BASE(); return { ...b,"event.subtype":"DISCONNECT","disconnect.reason":pick(["TIMEOUT","CLIENT_CRASH","SERVER_KICK"]),message:"Player "+b["player.id"]+" — DISCONNECT" }; },
    warn(){ const b=GAME_BASE(); return { ...b,"event.subtype":"MATCH_ABANDONED","match.result":"ABANDONED",message:"Player "+b["player.id"]+" — MATCH_ABANDONED" }; },
  };
  const GAME_MONETIZATION = {
    ok(){ return { "event.type":"IAP","player.id":"PLR-"+randDigits(8),"offer.id":"OFR-"+randAlnum(6),amount:+numBetween(0.99,99.99),currency:pick(["USD","EUR","GBP","JPY"]),latency_ms:intBetween(40,800),message:"IAP completed" }; },
    err(){ return { "event.type":"IAP_FAILED","error.code":pick(["RECEIPT_INVALID","PAYMENT_DECLINED","STORE_TIMEOUT"]),message:"IAP failed" }; },
    warn(){ return { "event.type":"IAP_FRAUD_FLAG","player.id":"PLR-"+randDigits(8),message:"IAP flagged for review" }; },
  };
  const GAME_LIVEOPS = {
    ok(){ return { "event.type":"LIVEOPS","event.id":"EVT-"+randAlnum(6),"players.online":intBetween(1000,250000),"server.region":pick(["NA","EU","APAC","LATAM","MEA"]),"cpu.pct":+numBetween(15,85),message:"Live ops heartbeat" }; },
    err(){ return { "event.type":"LIVEOPS_INCIDENT","incident.severity":pick(["SEV1","SEV2","SEV3"]),message:"Live ops incident opened" }; },
    warn(){ return { "event.type":"CAPACITY_WARNING","cpu.pct":+numBetween(85,99),message:"Server fleet near capacity" }; },
  };
  const GENERIC = { ok(){return {"event.type":"GENERIC_EVENT",message:"Generic business event"};},
    err(){return {"event.type":"GENERIC_ERROR",message:"Generic error event"};},
    warn(){return {"event.type":"GENERIC_WARN",message:"Generic warning event"};} };

  // ---- Cash & Valuables Management ----
  const CVM_TRANSIT = {
    ok(){ const id="SHP-"+randAlnum(10); const val=intBetween(10000,2000000);
      return {"event.type":"SHIPMENT_DISPATCHED","shipment.id":id,"vehicle.id":"VEH-"+randAlnum(6),"route.id":"RTE-"+randAlnum(6),"shipment.value":val,"crew.size":intBetween(2,4),"customer.id":"CUST-"+randDigits(5),region:pick(["NA","EU","APAC","MEA","LATAM"]),latency_ms:intBetween(30,500),message:"Shipment "+id+" dispatched — value $"+val}; },
    err(){ const id="SHP-"+randAlnum(10); const inc=pick(["ROBBERY_ATTEMPT","VEHICLE_BREAKDOWN","ACCIDENT","ROUTE_DEVIATION","COMMUNICATION_LOSS"]);
      return {"event.type":"TRANSIT_INCIDENT","shipment.id":id,"vehicle.id":"VEH-"+randAlnum(6),"incident.type":inc,"value.at.risk":intBetween(10000,1000000),"emergency.response":pick(["LAW_ENFORCEMENT","INTERNAL_RESPONSE","RECOVERY_CREW"]),message:"Incident on shipment "+id+": "+inc}; },
    warn(){ const id="SHP-"+randAlnum(10); const reason=pick(["TRAFFIC","WEATHER","ROUTE_CHANGE","MECHANICAL_CHECK","FUEL_STOP"]);
      return {"event.type":"SHIPMENT_DELAYED","shipment.id":id,"vehicle.id":"VEH-"+randAlnum(6),"delay.minutes":intBetween(5,120),"delay.reason":reason,message:"Shipment "+id+" delayed — reason: "+reason}; },
  };
  const CVM_VAULT = {
    ok(){ const t=pick(["DEPOSIT","WITHDRAWAL","TRANSFER","AUDIT"]); const amt=intBetween(1000,5000000);
      return {"event.type":"VAULT_TRANSACTION","vault.id":"VLT-"+randAlnum(6),"transaction.type":t,"transaction.amount":amt,"operator.id":"OPR-"+randDigits(5),"reconciliation.status":"BALANCED",latency_ms:intBetween(200,2000),message:"Vault "+t+" — $"+amt}; },
    err(){ const amt=intBetween(100,50000);
      return {"event.type":"VARIANCE_DETECTED","vault.id":"VLT-"+randAlnum(6),"variance.amount":amt,"variance.direction":pick(["OVER","SHORT"]),"reconciliation.status":"FAILED","escalated.to":pick(["SUPERVISOR","AUDIT_TEAM","MANAGEMENT"]),message:"Vault variance detected — "+amt+" USD discrepancy"}; },
    warn(){ const a=pick(["UNUSUAL_ACCESS_TIME","REPEATED_FAIL_AUTH","DUAL_CONTROL_VIOLATION","OVERRIDE_USED"]);
      return {"event.type":"ACCESS_ANOMALY","vault.id":"VLT-"+randAlnum(6),"alert.type":a,"operator.id":"OPR-"+randDigits(5),message:"Vault access anomaly: "+a}; },
  };
  const CVM_COUNTERFEIT = {
    ok(){ const d=pick([1,5,10,20,50,100,200]); const cnt=intBetween(10,5000);
      return {"event.type":"NOTE_VALIDATED","sensor.id":"SNS-"+randAlnum(6),denomination:d,"note.count":cnt,result:"AUTHENTIC","detection.method":pick(["UV_SCAN","MAGNETIC_INK","INFRARED","WATERMARK","MICRO_PRINT"]),latency_ms:intBetween(5,50),message:cnt+" × $"+d+" notes validated — AUTHENTIC"}; },
    err(){ const d=pick([20,50,100,200]); const cnt=intBetween(1,20);
      return {"event.type":"COUNTERFEIT_DETECTED","sensor.id":"SNS-"+randAlnum(6),denomination:d,"note.count":cnt,result:"COUNTERFEIT","detection.method":pick(["UV_SCAN","MAGNETIC_INK","INFRARED","WATERMARK"]),"forger.indicator":pick(["INKJET_PRINT","LASER_PRINT","PHOTOCOPY","DIGITAL_ALTERATION"]),message:cnt+" × $"+d+" counterfeit notes intercepted"}; },
    warn(){ const d=pick([20,50,100]); const cnt=intBetween(5,50); const score=+numBetween(0.55,0.79);
      return {"event.type":"SUSPICIOUS_BATCH","sensor.id":"SNS-"+randAlnum(6),denomination:d,"note.count":cnt,"confidence.score":score,result:"SUSPECT",message:"Suspicious batch: "+cnt+" × $"+d+" — confidence "+score}; },
  };

  // ---- Digital Retail Solutions ----
  const DR_TERMINAL = {
    ok(){ const st=pick(["ONLINE","ONLINE","ONLINE","IDLE"]);
      return {"event.type":"TERMINAL_HEARTBEAT","terminal.id":"TRM-"+randAlnum(8),"store.id":"STR-"+randDigits(5),"terminal.status":st,"transactions.since.reset":intBetween(0,500),"software.version":"v"+intBetween(8,12)+"."+intBetween(0,9)+"."+intBetween(0,9),connectivity:pick(["ETHERNET","WIFI","4G"]),"uptime.hours":+numBetween(0.5,720),latency_ms:intBetween(10,100),message:"Terminal heartbeat — status: "+st}; },
    err(){ const ec=pick(["NETWORK_TIMEOUT","HARDWARE_FAULT","SOFTWARE_CRASH","POWER_FAILURE","TAMPER_ALERT"]);
      return {"event.type":"TERMINAL_OFFLINE","terminal.id":"TRM-"+randAlnum(8),"store.id":"STR-"+randDigits(5),"terminal.status":"OFFLINE","error.code":ec,"failure.type":pick(["HARDWARE","SOFTWARE","NETWORK","POWER"]),message:"Terminal offline — "+ec}; },
    warn(){ const r=pick(["HIGH_LATENCY","PAPER_LOW","BATTERY_LOW","CONNECTIVITY_INTERMITTENT","SOFTWARE_OUTDATED"]);
      return {"event.type":"TERMINAL_DEGRADED","terminal.id":"TRM-"+randAlnum(8),"store.id":"STR-"+randDigits(5),"terminal.status":"DEGRADED","degradation.reason":r,message:"Terminal degraded — "+r}; },
  };
  const DR_SCO = {
    ok(){ const amt=+numBetween(5,300); const items=intBetween(1,30);
      return {"event.type":"SCO_TRANSACTION","session.id":uuidLike(),"lane.id":"SCO-"+randDigits(3),"store.id":"STR-"+randDigits(5),amount:amt,"item.count":items,"payment.method":pick(["CONTACTLESS","CHIP","CASH","MOBILE_PAY"]),"completion.time_ms":intBetween(30000,300000),"bagging.assists":intBetween(0,2),message:"SCO session completed — $"+amt+", "+items+" items"}; },
    err(){ const r=pick(["WEIGHT_DISCREPANCY","RESTRICTED_ITEM","PAYMENT_FAILED","AGE_VERIFICATION_FAILED","BARCODE_UNREADABLE"]);
      return {"event.type":"SCO_INTERVENTION_REQUIRED","session.id":uuidLike(),"lane.id":"SCO-"+randDigits(3),"store.id":"STR-"+randDigits(5),"intervention.reason":r,"attendant.id":"ATT-"+randDigits(4),message:"SCO intervention required — "+r}; },
    warn(){ return {"event.type":"SCO_ITEM_NOT_FOUND","session.id":uuidLike(),"lane.id":"SCO-"+randDigits(3),"store.id":"STR-"+randDigits(5),"barcode":randDigits(13),"manual.lookup.required":true,message:"SCO item not found — manual price lookup needed"}; },
  };
  const DR_LOYALTY = {
    ok(){ const pts=intBetween(10,500);
      return {"event.type":"LOYALTY_TRANSACTION","member.id":"MBR-"+randAlnum(10),"transaction.id":"TXN-"+randAlnum(12),"points.earned":pts,program:pick(["GOLD","SILVER","STANDARD","PREMIUM"]),tier:pick(["BRONZE","SILVER","GOLD","PLATINUM"]),"point.balance":intBetween(100,100000),"receipt.channel":pick(["EMAIL","SMS","APP","PRINT"]),"receipt.delivered":true,message:"Loyalty transaction — "+pts+" points earned"}; },
    err(){ const r=pick(["EXPIRED_VOUCHER","INSUFFICIENT_POINTS","MEMBER_NOT_FOUND","PROGRAM_INACTIVE","API_TIMEOUT"]);
      return {"event.type":"LOYALTY_REDEMPTION_FAILED","member.id":"MBR-"+randAlnum(10),"voucher.id":"VCH-"+randAlnum(8),"failure.reason":r,message:"Loyalty redemption failed — "+r}; },
    warn(){ const ch=pick(["EMAIL","SMS","APP"]);
      return {"event.type":"RECEIPT_DELIVERY_DELAYED","member.id":"MBR-"+randAlnum(10),"transaction.id":"TXN-"+randAlnum(12),"delivery.channel":ch,"delay.ms":intBetween(5000,60000),message:"Receipt delivery delayed — channel: "+ch}; },
  };

  // ---- ATM Managed Services ----
  const ATM_FLEET = {
    ok(){ const id="ATM-"+randAlnum(8); const cp=intBetween(30,100);
      return {"event.type":"ATM_HEARTBEAT","atm.id":id,location:pick(["BRANCH","RETAIL","AIRPORT","MALL","STREET","PETROL_STATION"]),"cash.level.pct":cp,"atm.status":"IN_SERVICE","uptime.hours":+numBetween(1,720),"transactions.today":intBetween(10,500),region:pick(["NA","EU","APAC","MEA","LATAM"]),latency_ms:intBetween(10,200),message:"ATM "+id+" heartbeat — cash: "+cp+"%"}; },
    err(){ const id="ATM-"+randAlnum(8); const r=pick(["HARDWARE_FAULT","NETWORK_FAILURE","CASH_JAM","CARD_READER_FAIL","POWER_OUTAGE","VANDALISM"]);
      return {"event.type":"ATM_OUT_OF_SERVICE","atm.id":id,location:pick(["BRANCH","RETAIL","AIRPORT","MALL","STREET"]),"atm.status":"OUT_OF_SERVICE","error.code":pick(["HW-001","HW-002","NET-001","CASH-001","CR-001"]),"failure.reason":r,region:pick(["NA","EU","APAC","MEA","LATAM"]),message:"ATM "+id+" out of service — "+r}; },
    warn(){ const id="ATM-"+randAlnum(8); const cp=intBetween(5,20); const h=+numBetween(0.5,6);
      return {"event.type":"LOW_CASH_ALERT","atm.id":id,location:pick(["BRANCH","RETAIL","AIRPORT","MALL","STREET"]),"cash.level.pct":cp,"hours.until.empty":h,"atm.status":"LOW_CASH",region:pick(["NA","EU","APAC","MEA","LATAM"]),message:"ATM "+id+" low cash — "+cp+"%, ~"+h+"h until empty"}; },
  };
  const ATM_REPLENISHMENT = {
    ok(){ const id="ATM-"+randAlnum(8); const amt=intBetween(5000,200000);
      return {"event.type":"REPLENISHMENT_COMPLETED","atm.id":id,"cassette.type":pick(["USD_20","USD_50","USD_100","EUR_20","EUR_50"]),"amount.loaded":amt,"crew.id":"CREW-"+randDigits(5),"duration.minutes":intBetween(5,30),"cash.level.after.pct":intBetween(80,100),message:"ATM "+id+" replenishment completed — $"+amt+" loaded"}; },
    err(){ const id="ATM-"+randAlnum(8); const r=pick(["CASSETTE_JAM","DENOMINATION_MISMATCH","SECURITY_ALERT","NETWORK_FAIL","VARIANCE_DETECTED"]);
      return {"event.type":"REPLENISHMENT_FAILED","atm.id":id,"cassette.type":pick(["USD_20","USD_50","USD_100"]),"failure.reason":r,"variance.amount":chance(0.5)?intBetween(50,5000):0,message:"ATM "+id+" replenishment failed — "+r}; },
    warn(){ const id="ATM-"+randAlnum(8); const dm=intBetween(10,120);
      return {"event.type":"REPLENISHMENT_DELAYED","atm.id":id,"delay.minutes":dm,"delay.reason":pick(["TRAFFIC","CREW_UNAVAILABLE","VEHICLE_ISSUE","SECURITY_HOLD"]),message:"ATM "+id+" replenishment delayed by "+dm+" min"}; },
  };
  const ATM_TRANSACTION = {
    ok(){ const id="ATMTXN-"+randAlnum(12); const t=pick(["CASH_WITHDRAWAL","BALANCE_INQUIRY","DEPOSIT","TRANSFER","PIN_CHANGE"]); const amt=t==="CASH_WITHDRAWAL"?intBetween(20,1000):0;
      return {"event.type":"ATM_TRANSACTION_COMPLETED","transaction.id":id,"transaction.type":t,"transaction.amount":amt,"atm.id":"ATM-"+randAlnum(8),"card.network":pick(["VISA","MASTERCARD","AMEX","INTERAC","MAESTRO"]),"card.type":pick(["DEBIT","CREDIT","PREPAID"]),"auth.latency_ms":intBetween(800,5000),latency_ms:intBetween(800,5000),message:t+" completed — txn "+id}; },
    err(){ const id="ATMTXN-"+randAlnum(12); const t=pick(["CASH_WITHDRAWAL","BALANCE_INQUIRY","DEPOSIT","TRANSFER"]); const r=pick(["INSUFFICIENT_FUNDS","CARD_BLOCKED","HOST_TIMEOUT","NETWORK_FAILURE","PIN_INCORRECT","CARD_EXPIRED"]);
      return {"event.type":"ATM_TRANSACTION_FAILED","transaction.id":id,"transaction.type":t,"failure.reason":r,"atm.id":"ATM-"+randAlnum(8),"card.network":pick(["VISA","MASTERCARD","AMEX","INTERAC","MAESTRO"]),"error.code":pick(["E001","E002","E003","E004","E005"]),message:"ATM transaction failed — "+r}; },
    warn(){ const a=pick(["SKIMMING_DETECTED","CARD_CLONING_ATTEMPT","SUSPICIOUS_SEQUENCE","HIGH_VELOCITY","GEO_MISMATCH"]);
      return {"event.type":"ATM_FRAUD_ALERT","atm.id":"ATM-"+randAlnum(8),"alert.type":a,"fraud.score":+numBetween(0.7,0.99),"action.taken":pick(["BLOCK_CARD","FLAG_REVIEW","NOTIFY_BANK","ALERT_SECURITY"]),message:"ATM fraud alert: "+a}; },
  };

  // ===== new verticals =====
  const VIN_CHARS = "ABCDEFGHJKLMNPRSTUVWXYZ0123456789";
  const randVin = () => Array.from({length:17},()=>VIN_CHARS[Math.floor(r()*VIN_CHARS.length)]).join("");
  const semver = () => "v"+intBetween(1,6)+"."+intBetween(0,12)+"."+intBetween(0,25);
  const AIRPORT_CODES = ["JFK","LAX","ORD","ATL","SFO","LHR","CDG","FRA","DXB","HND","SIN","SYD","GRU","DEL"];
  const randGate = () => pick("ABCDEF".split(""))+randDigits(2);

  const LOG_LASTMILE = {
    ok(){ const id="PKG-"+randDigits(10); const sub=pick(["DISPATCHED","OUT_FOR_DELIVERY","DELIVERED"]); const att=sub==="DELIVERED"?intBetween(1,2):1;
      return {"event.type":"DELIVERY_EVENT","package.id":id,"event.subtype":sub,"driver.id":"DRV-"+randDigits(5),"route.id":"RTE-"+randAlnum(6),
        zone:pick(["URBAN","SUBURBAN","RURAL","REMOTE"]),carrier:pick(["FEDEX","UPS","DHL","USPS","AMAZON_LOGISTICS","ONTRACK"]),
        "sla.type":pick(["SAME_DAY","NEXT_DAY","2_DAY","STANDARD"]),"sla.met":sub==="DELIVERED"?chance(0.88):true,"attempt.number":att,
        "estimated.delivery_ts":new Date(Date.now()+intBetween(60000,3600000)).toISOString(),"stop.sequence":intBetween(1,35),latency_ms:intBetween(50,3000),
        message:"Package "+id+" — "+sub}; },
    warn(){ const id="PKG-"+randDigits(10); return {"event.type":"DELIVERY_EVENT","package.id":id,"event.subtype":"DELIVERY_ATTEMPT",
      "driver.id":"DRV-"+randDigits(5),"route.id":"RTE-"+randAlnum(6),zone:pick(["URBAN","SUBURBAN","RURAL","REMOTE"]),
      carrier:pick(["FEDEX","UPS","DHL","USPS","AMAZON_LOGISTICS","ONTRACK"]),"sla.type":pick(["SAME_DAY","NEXT_DAY","2_DAY","STANDARD"]),
      "attempt.number":intBetween(2,3),"stop.sequence":intBetween(1,35),latency_ms:intBetween(50,3000),message:"Package "+id+" — DELIVERY_ATTEMPT"}; },
    err(){ const id="PKG-"+randDigits(10); const sub=pick(["FAILED_DELIVERY","RETURNED_TO_DEPOT"]);
      return {"event.type":"DELIVERY_EVENT","package.id":id,"event.subtype":sub,"driver.id":"DRV-"+randDigits(5),"route.id":"RTE-"+randAlnum(6),
        zone:pick(["URBAN","SUBURBAN","RURAL","REMOTE"]),carrier:pick(["FEDEX","UPS","DHL","USPS","AMAZON_LOGISTICS","ONTRACK"]),
        "sla.type":pick(["SAME_DAY","NEXT_DAY","2_DAY","STANDARD"]),"sla.met":false,"attempt.number":intBetween(1,3),
        "failure.reason":pick(["NOT_HOME","ACCESS_DENIED","ADDRESS_ERROR","DAMAGED","WEATHER"]),"stop.sequence":intBetween(1,35),
        latency_ms:intBetween(50,3000),message:"Package "+id+" — "+sub}; },
  };
  const LOG_WAREHOUSE_BASE = () => { const id="ITM-"+randDigits(8); const sub=pick(["INBOUND_SCAN","PUTAWAY","PICK","PACK","QUALITY_CHECK","OUTBOUND_SCAN"]); const zone=pick(["RECEIVING","STORAGE","PICKING","PACKING","DISPATCH","RETURNS"]);
    return {"event.type":"WAREHOUSE_EVENT","event.subtype":sub,"item.id":id,"warehouse.id":"WH-"+pick(["EAST","WEST","CENTRAL","NORTH","SOUTH"]),
      zone,"operator.id":"OPR-"+randDigits(4),"processing.time_ms":intBetween(500,15000),"conveyor.id":"CVR-"+randDigits(3),
      "throughput.rate":intBetween(200,2000),message:sub+" for item "+id+" in zone "+zone}; };
  const LOG_WAREHOUSE = { ok:LOG_WAREHOUSE_BASE,
    warn(){ return {...LOG_WAREHOUSE_BASE(),"event.subtype":"QUALITY_CHECK",message:"Quality hold opened"}; },
    err(){ return {...LOG_WAREHOUSE_BASE(),"event.subtype":"EXCEPTION","exception.type":pick(["MISMATCH","DAMAGED","LOST","OVERSIZE","HAZMAT"]),message:"Warehouse exception raised"}; } };
  const LOG_FLEET_BASE = () => ({"event.type":"FLEET_TELEMETRY","vehicle.id":"VEH-"+randAlnum(8),make:pick(["FORD","MERCEDES","ISUZU","VOLVO"]),"speed.kmh":intBetween(0,110),"odometer.km":intBetween(1000,350000),region:pick(["NA","EU","APAC"]),latency_ms:intBetween(20,800)});
  const LOG_FLEET = { ok(){ return {...LOG_FLEET_BASE(),"event.subtype":"HEARTBEAT",message:"Vehicle heartbeat"}; },
    warn(){ return {...LOG_FLEET_BASE(),"event.subtype":"MAINTENANCE_DUE",message:"Maintenance due soon"}; },
    err(){ return {...LOG_FLEET_BASE(),"event.subtype":"FAULT","fault.code":pick(["P0301","P0420","P0171","U0100"]),severity:pick(["MEDIUM","HIGH","CRITICAL"]),message:"Vehicle fault detected"}; } };

  const ENERGY_GRID_BASE = () => { const sub=pick(["LOAD_READING","VOLTAGE_ANOMALY","FREQUENCY_DEVIATION","SWITCH_OPERATION"]);
    return {"event.type":"GRID_EVENT","event.subtype":sub,"node.id":"GRD-"+randHex(8).toUpperCase(),
      "node.type":pick(["SUBSTATION","FEEDER","TRANSFORMER","SWITCH","METER_AGGREGATOR"]),
      region:pick(["NORTHEAST","SOUTHEAST","MIDWEST","WEST","SOUTHWEST"]),
      "load.mw":+numBetween(0.5,500),"voltage.kv":+numBetween(4,500),"frequency.hz":+numBetween(59.95,60.05),
      "customers.affected":0,severity:"INFO",message:sub+" on grid node"}; };
  const ENERGY_GRID = { ok:ENERGY_GRID_BASE,
    warn(){ const b=ENERGY_GRID_BASE(); return {...b,"event.subtype":pick(["VOLTAGE_ANOMALY","FREQUENCY_DEVIATION"]),"frequency.hz":+numBetween(59.85,59.95),"customers.affected":intBetween(50,5000),severity:"MINOR",message:"Anomaly detected on "+b["node.id"]}; },
    err(){ const customers=intBetween(500,50000); const b=ENERGY_GRID_BASE();
      return {...b,"event.subtype":"FAULT_DETECTED","customers.affected":customers,severity:pick(["MAJOR","CRITICAL"]),
        "auto.restored":chance(0.75),"restoration.time_ms":intBetween(500,1800000),
        message:"FAULT_DETECTED on "+b["node.id"]+" — "+customers+" customers affected"}; },
  };
  const ENERGY_OUTAGE_BASE = () => { const id="OUT-"+randDigits(8); const customers=intBetween(10,250000);
    return {"event.type":"OUTAGE_EVENT","outage.id":id,cause:pick(["EQUIPMENT_FAILURE","WEATHER","VEGETATION","ANIMAL","VEHICLE_IMPACT","UNKNOWN"]),
      "customers.affected":customers,region:pick(["NORTHEAST","SOUTHEAST","MIDWEST","WEST","SOUTHWEST"]),
      "estimated.restore_ts":new Date(Date.now()+intBetween(900000,28800000)).toISOString(),
      "regulatory.reportable":customers>10000}; };
  const ENERGY_OUTAGE = {
    ok(){ const b=ENERGY_OUTAGE_BASE(); const sub=pick(["CREW_DISPATCHED","FAULT_ISOLATED","RESTORATION_BEGIN","PARTIAL_RESTORE"]);
      return {...b,"event.subtype":sub,"crew.id":"CREW-"+randDigits(4),message:"Outage "+b["outage.id"]+" — "+sub}; },
    warn(){ const b=ENERGY_OUTAGE_BASE(); return {...b,"event.subtype":"OUTAGE_START",message:"Outage "+b["outage.id"]+" — OUTAGE_START"}; },
    err(){ const b=ENERGY_OUTAGE_BASE(); return {...b,"event.subtype":"RESTORED","mttr.minutes":intBetween(15,480),"crew.id":"CREW-"+randDigits(4),message:"Outage "+b["outage.id"]+" — RESTORED"}; },
  };
  const ENERGY_METER = {
    ok(){ return {"event.type":"METER_READ","meter.id":"MTR-"+randAlnum(10),"reading.kwh":+numBetween(0,60),region:pick(["NORTHEAST","SOUTHEAST","MIDWEST","WEST","SOUTHWEST"]),latency_ms:intBetween(10,600),message:"Meter read accepted"}; },
    warn(){ return {"event.type":"MISSED_READ","meter.id":"MTR-"+randAlnum(10),message:"Meter missed read window"}; },
    err(){ return {"event.type":"TAMPER_ALERT","meter.id":"MTR-"+randAlnum(10),"tamper.type":pick(["SEAL_BROKEN","MAGNETIC","REVERSE_FLOW"]),message:"Tamper alert raised"}; },
  };

  const AUTO_TELEMATICS_BASE = () => { const isEv=chance(0.4);
    return {"event.type":"VEHICLE_TELEMETRY","vehicle.id":"VIN-"+randVin(),make:pick(["TOYOTA","FORD","BMW","TESLA","GM","HONDA","VOLKSWAGEN","MERCEDES"]),
      "model.year":intBetween(2020,2026),region:pick(["NA","EU","APAC","LATAM"]),"speed.kmh":intBetween(0,200),
      "battery.pct":isEv?intBetween(0,100):null,"fuel.pct":isEv?null:intBetween(0,100),"ota.version":semver(),latency_ms:intBetween(50,2000)}; };
  const AUTO_TELEMATICS = {
    ok(){ const b=AUTO_TELEMATICS_BASE(); const sub=pick(["TRIP_START","TRIP_END","HEARTBEAT","DIAGNOSTIC"]); return {...b,"event.subtype":sub,message:"Vehicle "+b["vehicle.id"]+" — "+sub}; },
    warn(){ const b=AUTO_TELEMATICS_BASE(); return {...b,"event.subtype":"ALERT","alert.type":pick(["LOW_BATTERY","MAINTENANCE_DUE","RECALL_ACTIVE"]),"alert.severity":pick(["LOW","MEDIUM"]),message:"Vehicle "+b["vehicle.id"]+" — ALERT"}; },
    err(){ const b=AUTO_TELEMATICS_BASE(); const sub=pick(["ALERT","CRASH_DETECT"]);
      return {...b,"event.subtype":sub,"alert.type":sub==="CRASH_DETECT"?"COLLISION_RISK":pick(["ENGINE_FAULT","COLLISION_RISK"]),"alert.severity":pick(["HIGH","CRITICAL"]),message:"Vehicle "+b["vehicle.id"]+" — "+sub}; },
  };
  const AUTO_OTA_BASE = () => ({"event.type":"OTA_EVENT","vehicle.id":"VIN-"+randVin(),"firmware.version.from":semver(),"firmware.version.to":semver(),"package.size.mb":intBetween(50,2000),"download.speed.mbps":+numBetween(1,50),region:pick(["NA","EU","APAC","LATAM"])});
  const AUTO_OTA = {
    ok(){ const b=AUTO_OTA_BASE(); const sub=pick(["UPDATE_AVAILABLE","DOWNLOAD_START","DOWNLOAD_COMPLETE","INSTALL_START","INSTALL_SUCCESS"]); return {...b,"event.subtype":sub,message:"OTA "+sub+" for "+b["vehicle.id"]}; },
    warn(){ const b=AUTO_OTA_BASE(); return {...b,"event.subtype":"ROLLBACK","rollback.triggered":true,message:"OTA ROLLBACK for "+b["vehicle.id"]}; },
    err(){ const b=AUTO_OTA_BASE(); return {...b,"event.subtype":"INSTALL_FAIL","failure.reason":pick(["CONNECTIVITY","STORAGE","VALIDATION","POWER","TIMEOUT"]),"rollback.triggered":chance(0.3),message:"OTA INSTALL_FAIL for "+b["vehicle.id"]}; },
  };
  const AUTO_EV = {
    ok(){ return {"event.type":"EV_SESSION","session.id":"EV-"+randAlnum(10),"station.id":"STN-"+randDigits(5),"session.kwh":+numBetween(5,80),"session.minutes":intBetween(5,90),region:pick(["NA","EU","APAC","LATAM"]),revenue:+numBetween(2,35),message:"EV session completed"}; },
    warn(){ return {"event.type":"EV_THROTTLE","station.id":"STN-"+randDigits(5),message:"Charger throttled due to grid demand"}; },
    err(){ return {"event.type":"EV_SESSION_FAILED","station.id":"STN-"+randDigits(5),"fail.reason":pick(["AUTH_FAIL","HARDWARE","NETWORK","PAYMENT"]),message:"EV session failed"}; },
  };

  const POS_TXN_BASE = () => ({"event.type":"POS_TRANSACTION","transaction.id":"POS-"+randDigits(10),"terminal.id":"TRM-"+randAlnum(6),"store.id":"STR-"+randDigits(4),amount:+numBetween(1,500),"tender.type":pick(["CASH","CREDIT","DEBIT","CONTACTLESS","MOBILE_PAY","GIFT_CARD"]),"items.count":intBetween(1,20),"transaction.time_ms":intBetween(3000,45000),"operator.id":"OPR-"+randDigits(4),"loyalty.applied":chance(0.35)});
  const POS_TXN = {
    ok(){ const b=POS_TXN_BASE(); if(b["loyalty.applied"]) b["discount.pct"]=+numBetween(0,30); return {...b,"event.subtype":pick(["SALE","TENDER_CHANGE"]),message:"Sale on terminal "+b["terminal.id"]}; },
    warn(){ const b=POS_TXN_BASE(); return {...b,"event.subtype":"VOID",message:"VOID on terminal "+b["terminal.id"]}; },
    err(){ const b=POS_TXN_BASE(); return {...b,"event.subtype":"SALE","error.code":pick(["DECLINED","TIMEOUT","OFFLINE","PRINTER_FAIL"]),message:"Failed transaction"}; },
  };
  const POS_TERMINAL_BASE = () => { const status=pick(["ONLINE","OFFLINE","DEGRADED","UPDATING"]);
    return {"event.type":"TERMINAL_HEALTH","terminal.id":"TRM-"+randAlnum(6),"store.id":"STR-"+randDigits(4),"terminal.status":status,
      "uptime.pct":status==="OFFLINE"?0:+numBetween(95,100),"last.transaction.mins":intBetween(0,120),"software.version":"v"+randDigits(2)+"."+randDigits(2),
      region:pick(["NORTHEAST","SOUTHEAST","MIDWEST","WEST","SOUTHWEST"])}; };
  const POS_TERMINAL = {
    ok(){ const b=POS_TERMINAL_BASE(); return {...b,"event.subtype":pick(["HEARTBEAT","ONLINE"]),message:"Terminal "+b["terminal.id"]+" healthy"}; },
    warn(){ const b=POS_TERMINAL_BASE(); return {...b,"event.subtype":"PAPER_LOW","terminal.status":"DEGRADED",message:"Terminal paper low"}; },
    err(){ const b=POS_TERMINAL_BASE(); return {...b,"event.subtype":pick(["OFFLINE","PRINTER_ERROR"]),"terminal.status":"OFFLINE","uptime.pct":0,message:"Terminal offline"}; },
  };
  const POS_KITCHEN = {
    ok(){ return {"event.type":"KDS_EVENT","order.id":"KDS-"+randDigits(8),"station.id":pick(["GRILL","FRYER","SALAD","DRINKS","EXPO"]),"prep.time_ms":intBetween(60000,600000),message:"Order routed to KDS"}; },
    warn(){ return {"event.type":"KDS_DELAY","order.id":"KDS-"+randDigits(8),"station.id":pick(["GRILL","FRYER","SALAD","DRINKS","EXPO"]),message:"Order prep exceeding target"}; },
    err(){ return {"event.type":"KDS_ROUTING_FAILURE","order.id":"KDS-"+randDigits(8),"fail.reason":pick(["STATION_OFFLINE","PRINTER_FAIL","NETWORK"]),message:"Failed to route to kitchen"}; },
  };

  const AIRLINES_FLIGHT_BASE = () => { const air=pick(["AA","UA","DL","SW","BA","LH","AF","EK"]); const id="FLT-"+air+randDigits(4);
    return {"event.type":"FLIGHT_EVENT","flight.id":id,airline:air,origin:pick(AIRPORT_CODES),destination:pick(AIRPORT_CODES),
      "aircraft.type":pick(["B737","B777","B787","A320","A350","A380"]),passengers:intBetween(100,550),gate:randGate(),"on.time":chance(0.8)}; };
  const AIRLINES_FLIGHT = {
    ok(){ const b=AIRLINES_FLIGHT_BASE(); const sub=pick(["SCHEDULED","BOARDING","DEPARTED","AIRBORNE","LANDED","ARRIVED"]); return {...b,"event.subtype":sub,message:"Flight "+b["flight.id"]+" "+b.origin+"→"+b.destination+" — "+sub}; },
    warn(){ const b=AIRLINES_FLIGHT_BASE(); return {...b,"event.subtype":"DELAYED","delay.minutes":intBetween(15,240),"delay.reason":pick(["ATC","WEATHER","MECHANICAL","CREW","FUELING","CATERING","LATE_AIRCRAFT"]),"on.time":false,message:"Flight "+b["flight.id"]+" — DELAYED"}; },
    err(){ const b=AIRLINES_FLIGHT_BASE(); const sub=pick(["CANCELLED","DIVERTED"]); return {...b,"event.subtype":sub,"delay.reason":pick(["ATC","WEATHER","MECHANICAL","CREW"]),"on.time":false,message:"Flight "+b["flight.id"]+" — "+sub}; },
  };
  const AIRLINES_PAX_BASE = () => ({"event.type":"PASSENGER_EVENT","pax.id":"PAX-"+randDigits(8),"flight.id":"FLT-"+pick(["AA","UA","DL"])+randDigits(4),channel:pick(["WEB","MOBILE","KIOSK","COUNTER","AGENT"]),class:pick(["FIRST","BUSINESS","PREMIUM_ECONOMY","ECONOMY"]),"frequent.flyer":chance(0.25),"bag.count":intBetween(0,3),"processing.time_ms":intBetween(30000,600000)});
  const AIRLINES_PAX = {
    ok(){ const b=AIRLINES_PAX_BASE(); const sub=pick(["CHECK_IN","BAG_DROP","SECURITY_PASS","BOARDING","SETTLED","BAG_CLAIM","EXIT"]); return {...b,"event.subtype":sub,message:"Passenger "+b["pax.id"]+" — "+sub}; },
    warn(){ const b=AIRLINES_PAX_BASE(); return {...b,"event.subtype":pick(["CHECK_IN","BAG_DROP"]),exception:pick(["BAG_OVERWEIGHT","UPGRADE_PROCESSED","STANDBY_CLEARED"]),message:"Passenger "+b["pax.id"]+" exception"}; },
    err(){ const b=AIRLINES_PAX_BASE(); return {...b,"event.subtype":"CHECK_IN",exception:"DOCUMENT_ISSUE",message:"Document issue at check-in"}; },
  };
  const AIRLINES_GROUND = {
    ok(){ return {"event.type":"GROUND_OPS","flight.id":"FLT-"+pick(["AA","UA","DL"])+randDigits(4),stage:pick(["DEBOARDING","FUELING","CATERING","CLEANING","LOADING","READY"]),"turn.minutes":intBetween(20,120),gate:randGate(),message:"Ground op completed"}; },
    warn(){ return {"event.type":"GROUND_DELAY","flight.id":"FLT-"+pick(["AA","UA","DL"])+randDigits(4),stage:pick(["FUELING","CATERING"]),"delay.minutes":intBetween(5,30),message:"Turn delay detected"}; },
    err(){ return {"event.type":"GROUND_FAILURE","flight.id":"FLT-"+pick(["AA","UA","DL"])+randDigits(4),"fail.reason":pick(["EQUIPMENT","STAFFING","WEATHER"]),message:"Ground op failure"}; },
  };

  const IOT_FLEET_BASE = () => { const status=pick(["ONLINE","OFFLINE","DEGRADED","UPDATING","ERROR"]); const wired=chance(0.4);
    return {"event.type":"DEVICE_EVENT","device.id":"DEV-"+randHex(8),"device.type":pick(["SENSOR","GATEWAY","CAMERA","ACTUATOR","CONTROLLER","DISPLAY"]),
      "device.status":status,"firmware.version":semver(),"firmware.latest":chance(0.7),"signal.strength.dbm":intBetween(-90,-40),
      "battery.pct":wired?null:intBetween(0,100),"location.zone":pick(["FLOOR_1","FLOOR_2","WAREHOUSE","OUTDOOR","SERVER_ROOM","LOBBY"]),
      "uptime.hours":intBetween(0,8760),latency_ms:intBetween(10,5000)}; };
  const IOT_FLEET = {
    ok(){ const b=IOT_FLEET_BASE(); return {...b,"event.subtype":pick(["HEARTBEAT","ONLINE","CONFIG_CHANGE"]),message:"Device "+b["device.id"]+" healthy"}; },
    warn(){ const b=IOT_FLEET_BASE(); return {...b,"event.subtype":"ALERT","alert.type":pick(["LOW_BATTERY","SIGNAL_LOSS","MEMORY_LOW"]),message:"Device alert"}; },
    err(){ const b=IOT_FLEET_BASE(); return {...b,"device.status":"OFFLINE","event.subtype":pick(["OFFLINE","ALERT"]),"alert.type":pick(["OFFLINE","TAMPERING","OVERTEMP"]),message:"Device critical"}; },
  };
  const IOT_SENSOR_READING = () => { const t=pick(["TEMPERATURE","PRESSURE","HUMIDITY","VIBRATION","FLOW","CURRENT","PROXIMITY"]);
    let v,u; switch(t){case "TEMPERATURE":v=+numBetween(15,120);u="CELSIUS";break;case "PRESSURE":v=+numBetween(0,150);u="BAR";break;
      case "HUMIDITY":v=+numBetween(20,95);u="PERCENT";break;case "VIBRATION":v=+numBetween(0,20);u="G";break;
      case "FLOW":v=+numBetween(0,500);u="LPS";break;case "CURRENT":v=+numBetween(0,100);u="AMPS";break;default:v=+numBetween(0,1000);u="MM";}
    return {"sensor.id":"SNS-"+randHex(8),"sensor.type":t,"reading.value":v,"reading.unit":u,"plant.id":"PLT-"+randDigits(3),"asset.id":"AST-"+randAlnum(6)}; };
  const IOT_SENSOR = {
    ok(){ const r2=IOT_SENSOR_READING(); return {"event.type":"SENSOR_READING",...r2,"threshold.breach":false,"maintenance.due":chance(0.08),"anomaly.score":+numBetween(0,0.4),message:"Sensor "+r2["sensor.id"]+" reading"}; },
    warn(){ const r2=IOT_SENSOR_READING(); return {"event.type":"SENSOR_READING",...r2,"threshold.breach":true,"threshold.type":pick(["HIGH","LOW","RATE_OF_CHANGE"]),"anomaly.score":+numBetween(0.5,0.79),message:"Sensor threshold breach"}; },
    err(){ const r2=IOT_SENSOR_READING(); return {"event.type":"SENSOR_ANOMALY",...r2,"threshold.breach":true,"threshold.type":"RATE_OF_CHANGE","anomaly.score":+numBetween(0.85,1.0),message:"Sensor anomaly"}; },
  };
  const IOT_FIRMWARE_BASE = () => ({"event.type":"FIRMWARE_EVENT","device.id":"DEV-"+randHex(8),"firmware.version.from":semver(),"firmware.version.to":semver(),region:pick(["NA","EU","APAC"])});
  const IOT_FIRMWARE = {
    ok(){ return {...IOT_FIRMWARE_BASE(),"event.subtype":"INSTALL_SUCCESS",message:"Firmware install succeeded"}; },
    warn(){ return {...IOT_FIRMWARE_BASE(),"event.subtype":"ROLLBACK",message:"Firmware rolled back"}; },
    err(){ return {...IOT_FIRMWARE_BASE(),"event.subtype":"INSTALL_FAIL","fail.reason":pick(["VALIDATION","POWER","STORAGE","TIMEOUT"]),message:"Firmware install failed"}; },
  };

  const MEDIA_PLAYBACK_BASE = () => ({"event.type":"PLAYBACK_EVENT","session.id":"SES-"+randAlnum(12),"viewer.id":"VWR-"+randDigits(8),"content.id":"CNT-"+randAlnum(8),"content.type":pick(["LIVE","VOD","TRAILER","SHORT_FORM"]),quality:pick(["4K","1080P","720P","480P","360P","AUTO"]),"cdn.pop":pick(["US-EAST","US-WEST","EU-WEST","EU-CENTRAL","APAC-EAST","APAC-SE"]),"device.type":pick(["SMART_TV","MOBILE","TABLET","WEB","STB"]),"bitrate.kbps":intBetween(400,20000),"rebuffering.ratio":+numBetween(0,0.05)});
  const MEDIA_PLAYBACK = {
    ok(){ const b=MEDIA_PLAYBACK_BASE(); const sub=pick(["PLAY_REQUEST","MANIFEST_FETCH","SEGMENT_REQUEST","SESSION_END"]); const ex={}; if(sub==="PLAY_REQUEST") ex["startup.time_ms"]=intBetween(500,8000);
      return {...b,...ex,"event.subtype":sub,message:"Session "+b["session.id"]+" — "+sub}; },
    warn(){ const b=MEDIA_PLAYBACK_BASE(); return {...b,"event.subtype":pick(["BUFFER_START","BUFFER_END"]),"buffering.duration_ms":intBetween(500,30000),"rebuffering.ratio":+numBetween(0.05,0.15),message:"Session buffering"}; },
    err(){ const b=MEDIA_PLAYBACK_BASE(); return {...b,"event.subtype":"PLAYBACK_ERROR","error.code":pick(["404","502","SEGMENT_MISSING","DRM_FAIL","TIMEOUT"]),message:"PLAYBACK_ERROR"}; },
  };
  const MEDIA_LIVE = {
    ok(){ return {"event.type":"LIVE_STREAM","stream.id":"LIV-"+randAlnum(8),"cdn.pop":pick(["US-EAST","US-WEST","EU-WEST","APAC-EAST"]),viewers:intBetween(1000,500000),"encoder.health":pick(["GREEN","GREEN","AMBER"]),"bitrate.kbps":intBetween(2000,12000),message:"Live stream healthy"}; },
    warn(){ return {"event.type":"LIVE_DEGRADATION","stream.id":"LIV-"+randAlnum(8),"cdn.pop":pick(["US-EAST","US-WEST","EU-WEST","APAC-EAST"]),"encoder.health":"AMBER",message:"Live stream degraded"}; },
    err(){ return {"event.type":"LIVE_ERROR","stream.id":"LIV-"+randAlnum(8),"encoder.health":"RED","error.code":pick(["ENCODER_DROP","ORIGIN_FAIL","SEGMENT_LOSS"]),message:"Live stream error"}; },
  };
  const MEDIA_AD_BASE = () => ({"event.type":"AD_EVENT","session.id":"SES-"+randAlnum(12),"ad.id":"AD-"+randAlnum(8),"ad.type":pick(["PRE_ROLL","MID_ROLL","POST_ROLL","OVERLAY"]),advertiser:pick(["BRAND_A","BRAND_B","BRAND_C","BRAND_D","BRAND_E"]),"ad.duration_ms":intBetween(15000,60000),"fill.rate":+numBetween(0.7,1),"decision.latency_ms":intBetween(5,500),"revenue.cpm":+numBetween(1,50),"skip.eligible":chance(0.5)});
  const MEDIA_AD = {
    ok(){ const b=MEDIA_AD_BASE(); return {...b,"event.subtype":pick(["AD_REQUEST","AD_DECISION","AD_LOADED","AD_STARTED","AD_COMPLETED"]),message:"Ad event"}; },
    warn(){ const b=MEDIA_AD_BASE(); return {...b,"event.subtype":"AD_SKIPPED",message:"Ad skipped"}; },
    err(){ const b=MEDIA_AD_BASE(); return {...b,"event.subtype":"AD_ERROR","error.type":pick(["TIMEOUT","NO_FILL","INVALID_VAST","NETWORK"]),message:"Ad error"}; },
  };

  return {
    "financial/payments":FIN_PAYMENTS,"financial/fraud":FIN_FRAUD,"financial/trading":FIN_TRADING,
    "healthcare/patient_portal":HC_PORTAL,"healthcare/claims":HC_CLAIMS,"healthcare/ehr":HC_EHR,
    "retail/orders":RETAIL_ORDERS,"retail/inventory":RETAIL_INVENTORY,"retail/cx":RETAIL_CX,
    "telco/network":TELCO_NETWORK,"telco/billing":TELCO_BILLING,"telco/care":TELCO_CARE,
    "manufacturing/production":MFG_PRODUCTION,"manufacturing/quality":MFG_QUALITY,"manufacturing/supply_chain":MFG_SUPPLY,
    "insurance/claims":INS_CLAIMS,"insurance/underwriting":INS_UW,"insurance/policy":INS_POLICY,
    "gaming/sessions":GAME_SESSIONS,"gaming/monetization":GAME_MONETIZATION,"gaming/live_ops":GAME_LIVEOPS,
    "logistics/last_mile":LOG_LASTMILE,"logistics/warehouse":LOG_WAREHOUSE,"logistics/fleet":LOG_FLEET,
    "energy/smart_grid":ENERGY_GRID,"energy/outage":ENERGY_OUTAGE,"energy/metering":ENERGY_METER,
    "automotive/telematics":AUTO_TELEMATICS,"automotive/ota_updates":AUTO_OTA,"automotive/ev_charging":AUTO_EV,
    "pos/transactions":POS_TXN,"pos/terminal_health":POS_TERMINAL,"pos/kitchen":POS_KITCHEN,
    "airlines/flight_ops":AIRLINES_FLIGHT,"airlines/passenger":AIRLINES_PAX,"airlines/ground_ops":AIRLINES_GROUND,
    "iot/device_fleet":IOT_FLEET,"iot/sensor_telemetry":IOT_SENSOR,"iot/firmware":IOT_FIRMWARE,
    "media/video_delivery":MEDIA_PLAYBACK,"media/live_streaming":MEDIA_LIVE,"media/ad_insertion":MEDIA_AD,
    "cash_valuables/cash_in_transit":CVM_TRANSIT,"cash_valuables/vault_operations":CVM_VAULT,"cash_valuables/counterfeit_detection":CVM_COUNTERFEIT,
    "digital_retail/terminal_management":DR_TERMINAL,"digital_retail/self_checkout":DR_SCO,"digital_retail/loyalty_receipts":DR_LOYALTY,
    "atm_services/atm_fleet_health":ATM_FLEET,"atm_services/cash_replenishment":ATM_REPLENISHMENT,"atm_services/atm_transactions":ATM_TRANSACTION,
    "__default__":GENERIC,
  };
})()`;

export const buildWorkflowDescriptor = (
  cfg: GeneratorConfig,
  documentId?: string,
): WorkflowDescriptor => {
  const script = buildJavaScriptTaskCode(cfg);
  const created = new Date().toISOString();
  // Pipe-delimited metadata embedded in description so the Deployments page
  // can parse it back. Keep this format stable — see Deployments.tsx parser.
  const description =
    `LaunchLog | vertical:${cfg.vertical} | usecase:${cfg.useCase} | scenario:${cfg.scenarioName}` +
    ` | created:${created}` +
    (documentId ? ` | documentId:${documentId}` : "");
  return {
    title: `[LaunchLog] ${cfg.scenarioName}`,
    description,
    isPrivate: false,
    trigger: {
      schedule: {
        isActive: true,
        isFaulty: false,
        trigger: { type: "cron", cron: "*/1 * * * *" },
        rule: null,
        filterParameters: {},
        timezone: "UTC",
        inputs: {},
      },
    },
    tasks: {
      generate_and_ingest: {
        name: "generate_and_ingest",
        action: "dynatrace.automations:run-javascript",
        timeout: 120,
        position: { x: 0, y: 1 },
        retry: { count: 2, delay: 5 },
        input: { script },
      },
    },
  };
};

export const _internal = { escapeForTemplateLiteral };
